# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin:$HOME/.bin
PS1='[\u@\h] (\w) $ '
export PS1
export PATH
alias yo='echo yo'
alias fsort='du -hs ./* | sort -rh | head -n 5'
export ANSIBLE_SSH_ARGS=
