# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
PATH=$HOME/.bin:$HOME/git/ansible/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin

PYTHONPATH=$HOME/git/ansible/lib:
MANPATH=/home/JC/admin.ju/git/ansible/docs/man:

PS1='[\u@\h] (\w) $ '
export PS1
export PATH
export PYTHONPATH
export MANPATH
alias fsort='du -hs ./* | sort -rh | head -n 5'
set -o vi
export ANSIBLE_SSH_ARGS=
#alias vi='vim -S ~/.vim/session'
